// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaffManagement1.DataAccess;

#nullable disable

namespace StaffManagement1.DataAccess.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220107181533_PhotoCreted")]
    partial class PhotoCreted
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StaffManagement1.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 1,
                            Email = "Ruzimurodabdunazarov@mail.ru",
                            FirstName = "Ro'zimurod",
                            LastName = "Abdunazarov"
                        },
                        new
                        {
                            Id = 2,
                            Department = 4,
                            Email = "Bob_tristand@mail.ru",
                            FirstName = "Bob",
                            LastName = "Struard"
                        },
                        new
                        {
                            Id = 3,
                            Department = 2,
                            Email = "Choriyev2006@mail.ru",
                            FirstName = "Shoxob",
                            LastName = "Choriyev"
                        },
                        new
                        {
                            Id = 4,
                            Department = 3,
                            Email = "Niginochka@mail.ru",
                            FirstName = "Nigina",
                            LastName = "Shomurodova"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
